const pg = require('pg');
const connectionString = process.env.DATABASE_URL || 'postgres://localhost:5432/chatter';

const client = new pg.Client(connectionString);
client.connect();

const createMessagesTableQuery = `
  CREATE TABLE messages (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP default current_timestamp,
    room_id TEXT,
    nickname TEXT,
    avatar TEXT,
    body TEXT
  )
`

// CREATE MESSAGES TABLE
// client.query(createMessagesTableQuery)
//   .then(() => client.end())
//   .catch(console.log)

const createMessageQuery = `
  INSERT INTO messages(room_id, nickname, avatar, body) values($1, $2, $3, $4)
`

const writeMessage = (room_id, nickname, avatarUrl, body) =>
  client.query(createMessageQuery, [room_id, nickname, avatarUrl, body])
    .then(() => client.end())
    .catch(console.log)


const getMessagesQuery = `
  SELECT * FROM messages WHERE room_id = $1 ORDER BY id ASC
`

const getMessages = (room_id) =>
  client.query(getMessagesQuery, [room_id])
    .then(console.log)
    .then(() => client.end())
    .catch(console.log)
