const db = require('./index')

const createMessagesTableQuery = `
  CREATE TABLE messages (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP default current_timestamp,
    room_id TEXT,
    nickname TEXT,
    avatar TEXT,
    body TEXT
  )
`

// CREATE MESSAGES TABLE
// client.query(createMessagesTableQuery)
//   .then(() => client.end())
//   .catch(console.log)

const writeMessageQuery = `
  INSERT INTO messages(room_id, nickname, avatar, body) values($1, $2, $3, $4) returning *
`

const writeMessage = (room_id, nickname, avatarUrl, body) =>
  db.query(writeMessageQuery, [room_id, nickname, avatarUrl, body])
    .catch(console.log)


const getMessagesQuery = `
  SELECT * FROM messages WHERE room_id = $1 ORDER BY id ASC
`

const getMessages = (room_id) =>
  db.query(getMessagesQuery, [room_id])
    .then(r => r.rows)
    .catch(console.log)

module.exports = {
  getMessages,
  writeMessage
}
